// Writes the contracts' ABIs into the API (apps/api/src/v1/chain/abis.ts), from the Foundry build.
// Run after changing a contract: cd contracts && forge build && node scripts/export-abis.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "out");
const abi = (file, name) => JSON.parse(readFileSync(join(out, file, `${name}.json`), "utf8")).abi;
const contracts = { creatorEscrow: abi("CreatorEscrow.sol", "CreatorEscrow"), creatorFund: abi("CreatorFund.sol", "CreatorFund"), erc20: abi("IERC20.sol", "IERC20") };
const body = Object.entries(contracts)
  .map(([name, value]) => `export const ${name}Abi = ${JSON.stringify(value, null, 2)} as const;`)
  .join("\n\n");
writeFileSync(join(here, "..", "..", "apps", "api", "src", "v1", "chain", "abis.ts"), `// Generated by contracts/scripts/export-abis.mjs from the Foundry build. Don't edit by hand.\n\n${body}\n`);
console.log("wrote apps/api/src/v1/chain/abis.ts");
